In [1]:
pwd

'C:\\Users\\iibm'

In [2]:
print ("workshop on python")

workshop on python


In [3]:
print ('zhi')

zhi


In [4]:
print('a\'a\'')

a'a'


In [5]:
print('''a 'anisha' ''')

a 'anisha' 


In [6]:
print('''
data
science
zhi
''')


data
science
zhi



# Arithmetic Operation

In [7]:
2+5

7

In [8]:
4/2

2.0

In [9]:
4//2

2

In [10]:
2e2

200.0

In [11]:
5*5

25

In [12]:
5*5+8*2

41

In [13]:
(5+5)*2

20

In [14]:
x=10
x

10

In [15]:
x=20


In [16]:
x

20

In [17]:
type(x)

int

In [18]:
print(type(x))

<class 'int'>


In [19]:
s='workshop'

In [20]:
s

'workshop'

# Slicing and Indexing

In [21]:
s[start:end:step]

NameError: name 'start' is not defined

s[start:end:step]

In [22]:
s[:]

'workshop'

In [23]:
s[: :]

'workshop'

In [24]:
s[5]

'h'

In [25]:
s[:5]

'works'

In [26]:
s[3:]

'kshop'

In [27]:
s[: :2]

'wrso'

In [28]:
s[: :-1]

'pohskrow'

# Methods

In [29]:
s=s.upper()

In [30]:
s

'WORKSHOP'

In [31]:
s.lower()

'workshop'

split

In [32]:
'data'.split()

['data']

In [33]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [35]:
'A B C D E'.split('C')

['A B ', ' D E']

In [36]:
s.split('S')

['WORK', 'HOP']

In [37]:
name='Anisha'
marks=90

In [40]:
print(name+str(marks))

Anisha90


# Formating

In [41]:
print ('this is a %s pen','ram')

this is a %s pen ram


In [42]:
print('this is a %s pen %s' %('ram','abc'))

this is a ram pen abc


# List

In [43]:
                                                                                                                                                                                                                                            my_list'A B C D' .split()                                                                                                                          

SyntaxError: invalid syntax (<ipython-input-43-3bffef0d544a>, line 1)

In [44]:
my_list='A B C D'.split()                                                                                                                        

In [45]:
my_list

['A', 'B', 'C', 'D']

In [46]:
mylist=['a',5, 5.3]

In [47]:
mylist

['a', 5, 5.3]

In [48]:
print(type(mylist))

<class 'list'>


# Slicing and indexing

In [49]:
mylist[1]

5

In [50]:
mylist[0:2]

['a', 5]

In [51]:
mylist[0:3:1]

['a', 5, 5.3]

In [52]:
mylist[0:3:2]

['a', 5.3]

In [53]:
mylist*2

['a', 5, 5.3, 'a', 5, 5.3]

In [54]:
mylist=mylist + ['a']

In [55]:
mylist

['a', 5, 5.3, 'a']

# LIST METHOD

In [57]:
l=[1,2,3,4,5]

In [58]:
l

[1, 2, 3, 4, 5]

In [59]:
l.append('A B C' .split())

In [60]:
l

[1, 2, 3, 4, 5, ['A', 'B', 'C']]

In [62]:
l.append('A')

In [63]:
l

[1, 2, 3, 4, 5, ['A', 'B', 'C'], 'A']

In [65]:
print(l)

[1, 2, 3, 4, 5, ['A', 'B', 'C'], 'A']


In [66]:
list1=[1,2,3,4,5]

In [67]:
list1

[1, 2, 3, 4, 5]

In [68]:
print(list)

<class 'list'>


In [69]:
print(type(list))

<class 'type'>


In [72]:
list1.append('a')
list1

[1, 2, 3, 4, 5, 'a', 'a', 'a']

In [73]:
list1.pop(2)

3

In [75]:
l1=[1,2,3]
l2=[4,5,6]
l3=[6,7,8]

In [78]:
matrix=[l1,l2,l3]

In [79]:
matrix

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [80]:
type(matrix)

list

In [81]:
matrix[1] [0]

4

In [82]:
len(matrix)

3

# Touple


In [97]:
t1=(1,2,3,3,3,3)

In [98]:
t1

(1, 2, 3, 3, 3, 3)

In [85]:
type(t1)

tuple

In [86]:
print(type(t1))

<class 'tuple'>


In [87]:
t1

(1, 2, 3)

In [88]:
t1[2]='a'

TypeError: 'tuple' object does not support item assignment

In [89]:
l2=[1,2,3]

In [90]:
l2[2]=5

In [92]:
l2

[1, 2, 5]

In [93]:
t1[1]

2

In [94]:
t1[-1]

3

# Touple method

In [95]:
t1.index(2)

1

In [99]:
t1.count(3)

4

# Dictionary

In [100]:
disc1={1:'a',2:'b',3:'c'}

In [101]:
disc1

{1: 'a', 2: 'b', 3: 'c'}

In [102]:
type(disc1)

dict

In [103]:
print(type(disc1))

<class 'dict'>


In [104]:
disc1[1]

'a'

In [105]:
disc1[2]

'b'

In [106]:
disc1[4]='ram'

In [107]:
disc1

{1: 'a', 2: 'b', 3: 'c', 4: 'ram'}

# NESTED DICTIONARY

In [108]:
disc1={1: 'a',2: 'b', 'key1':{1: 'a',2: 'hello',3:'c'},3:'c'}

In [109]:
disc1

{1: 'a', 2: 'b', 'key1': {1: 'a', 2: 'hello', 3: 'c'}, 3: 'c'}

In [110]:
disc1['key1'][2][2]

'l'

In [111]:
disc1['key1'][2]

'hello'

# METHOD


In [112]:
disc1.keys()

dict_keys([1, 2, 'key1', 3])

In [113]:
disc1.values()

dict_values(['a', 'b', {1: 'a', 2: 'hello', 3: 'c'}, 'c'])

In [114]:
disc1.items()

dict_items([(1, 'a'), (2, 'b'), ('key1', {1: 'a', 2: 'hello', 3: 'c'}), (3, 'c')])

# SET

# Unodered collection

In [115]:
x=set()

In [116]:
x

set()

In [117]:
set()

set()

In [118]:
print(type(x))

<class 'set'>


In [119]:
x.add(1)

In [120]:
x

{1}

In [124]:
list2=[1,2,3,1,2,3,2,2,3,4]

In [125]:
list2

[1, 2, 3, 1, 2, 3, 2, 2, 3, 4]

In [126]:
set(list2)

{1, 2, 3, 4}

### Boolean

In [127]:
True

True

In [128]:
False

False

In [129]:
None

In [130]:
list3=[1,2,[3,4,'hello']]

In [131]:
list3

[1, 2, [3, 4, 'hello']]

In [133]:
list3[2][2]

'hello'

In [135]:
list3[2][2]='goodbye'

In [136]:
list3

[1, 2, [3, 4, 'goodbye']]

In [137]:
list5=[1,2,2,33,4,4,11,22,3,3,2]

In [138]:
list5

[1, 2, 2, 33, 4, 4, 11, 22, 3, 3, 2]

In [139]:
set(list5)

{1, 2, 3, 4, 11, 22, 33}

## Membership Operation

In [140]:
m='zhipatna'

In [141]:
m

'zhipatna'

In [142]:
'p' in m

True

In [143]:
't' not in m

False

In [144]:
x=100

In [145]:
y=100

In [146]:
x is y

True

In [147]:
x is not y

False

In [148]:
list1=[1,2,3]

In [149]:
list2=[1,2,3]

In [150]:
list1 is list2

False

In [151]:
list1==list2

True

# Numerical Python

In [152]:
import numpy as np

In [154]:
x= [1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [155]:
type(x)

list

In [156]:
y=np.array(x)

In [157]:
type(y)

numpy.ndarray

In [158]:
x2=(1,2,3,'NTELIT',3.4)

In [159]:
np.array(x2)

array(['1', '2', '3', 'NTELIT', '3.4'], dtype='<U11')

# Linspace

In [160]:
np.linspace(start=0, stop=20, num=10, endpoint=False,retstep=True)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0)

In [161]:
np.linspace(start=0, stop=20, num=10, endpoint=True,retstep=True)

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

# Arange

In [162]:
np.arange(start=0,stop=50,step=5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [163]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [164]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [165]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

# Create 3*3 Array

In [168]:
z=[[1,2,3],[4,5,6],[7,8,9]]

In [169]:
z

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [170]:
y=np.array(z)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [172]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [173]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Reshaping

In [174]:
x=np.array([0,1,2,3,4,5,6,7,8,9])

In [175]:
x #1*10 type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Convert to 5*2

In [176]:
x.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [177]:
x.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [178]:
x.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [179]:
x.reshape((2,10))

ValueError: cannot reshape array of size 10 into shape (2,10)

# Sliceing

In [180]:
a = np.arange(10)

In [181]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
s = slice(2,7)

In [183]:
a[s]

array([2, 3, 4, 5, 6])

In [184]:
s1=slice(2,7,2)

In [185]:
a[s1]

array([2, 4, 6])

In [186]:
a[2:7]

array([2, 3, 4, 5, 6])

In [187]:
a[2:7:2]

array([2, 4, 6])

# Random Number Generation

In [188]:
np.random.rand(5)

array([0.04015275, 0.54710477, 0.98677147, 0.27816293, 0.10424141])

In [189]:
np.random.rand(5)

array([0.53473871, 0.37875005, 0.09569342, 0.45247837, 0.60886057])

# Normal Distribution

In [190]:
np.random.rand(5,4)

array([[0.15850893, 0.04357724, 0.29970736, 0.7722484 ],
       [0.48999832, 0.69517261, 0.82642486, 0.88650143],
       [0.86186218, 0.11903268, 0.25282064, 0.77783864],
       [0.57877754, 0.80647411, 0.06710266, 0.99687745],
       [0.99806437, 0.51492563, 0.90428891, 0.4084804 ]])

# Randint

In [191]:
np.random.randint(low=0,high=100)

64

In [192]:
# 4 digit Random Number
np.random.randint(low=1000,high=9999)

1088

In [193]:
np.random.randint(low=1000,high=9999,size=10)

array([1740, 3499, 4140, 6801, 6018, 7472, 6270, 6629, 1171, 8105])

# Seed

In [197]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [198]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [199]:
pwd

'C:\\Users\\iibm'